#!/bin/sh

lowercase(){
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
}

OS=`lowercase \`uname -s\``
# KERNEL=`uname -r`
MACH=`uname -m`

archive_file="daccord_${OS}_${MACH}.tgz"
version_file="version_${OS}_${MACH}.h"
history_file="history_${OS}_${MACH}.txt"

cp -f appversion.h ${version_file}
cp -f History.txt ${history_file}

tar -zcf ${archive_file} daccord History.txt License.txt daccord.sh server_cert.pem updatebeta updaterelease www/ scripts/ Config/ plugins/ dzVents/

# Cleaning up
rm -f ${version_file}
rm -f ${history_file}

echo "Done!...";
exit 0;
