#!/bin/sh

# This script can be used to upgrade to the latest beta version

lowercase(){
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
}

OS=`lowercase \`uname -s\``
MACH=`uname -m`
if [ ${MACH} = "armv6l" ]
then
 MACH="armv7l"
fi

echo "Updating to latest beta version..."
echo "Please Standby..."
wget -O daccord_beta.tgz "http://ivmech.com/daccord/beta/daccord_${OS}_${MACH}.tgz"
tar xvfz daccord_beta.tgz
rm daccord_beta.tgz
echo "Restarting Daccord... (please standby...)"
sudo service daccord.sh restart
