#!/bin/sh

# This script can be used to upgrade to the latest release version

lowercase(){
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
}

OS=`lowercase \`uname -s\``
MACH=`uname -m`
if [ ${MACH} = "armv6l" ]
then
 MACH="armv7l"
fi

echo "Updating to latest release version..."
echo "Please Standby..."
wget -O daccord_release.tgz "http://ivmech.com/daccord/release/daccord_${OS}_${MACH}.tgz"
tar xvfz daccord_release.tgz
rm daccord_release.tgz
echo "Restarting Daccord... (please standby...)"
sudo service daccord.sh restart
